#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Tue May 28 11:33:32 2019
#

import wx
import wx.grid
import os
from WalkDirectory import WalkDirectory
from components import ConfigureData

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from VTKPanel import VTKPanel
# end wxGlade


class _3DWarehouseFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: _3DWarehouseFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1024, 768))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.windowStlRender = VTKPanel(self.panel_1)
        self.txtPath = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.button_Path_selection = wx.Button(self.panel_1, wx.ID_ANY, "...")
        self.treeDir = wx.TreeCtrl(self.panel_1, wx.ID_ANY)
        self.gridDataInfo = wx.grid.Grid(self.panel_1, wx.ID_ANY, size=(1, 1))
        self.button_close = wx.Button(self.panel_1, wx.ID_ANY, "Close")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnPathSelection, self.button_Path_selection)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.onTreeChange, self.treeDir)
        self.Bind(wx.EVT_TREE_SEL_CHANGING, self.onTreeChanging, self.treeDir)
        self.Bind(wx.EVT_BUTTON, self.OnClose, self.button_close)
        # end wxGlade

        # Load and set configuration data
        self.configData = ConfigureData()
        self.configData.Load()
        self.LoadWolkDirTree()

        self.GridDataInfo()


    def __set_properties(self):
        # begin wxGlade: _3DWarehouseFrame.__set_properties
        self.SetTitle("3D Warehouse")
        self.txtPath.SetBackgroundColour(wx.Colour(127, 255, 0))
        self.txtPath.Enable(False)
        self.button_Path_selection.SetMinSize((28, 26))
        self.gridDataInfo.CreateGrid(0, 0)
        self.gridDataInfo.SetMinSize((400, 100))
        self.gridDataInfo.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: _3DWarehouseFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Directory"), wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.windowStlRender, 2, wx.EXPAND, 0)
        sizer_4.Add(self.txtPath, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 0)
        sizer_6.Add((0, 0), 0, 0, 0)
        sizer_6.Add((0, 0), 0, 0, 0)
        sizer_6.Add(self.button_Path_selection, 0, 0, 0)
        sizer_4.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_4.Add(self.treeDir, 1, wx.ALL | wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 4)
        sizer_2.Add(self.gridDataInfo, 0, wx.ALL | wx.EXPAND, 2)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add(self.button_close, 0, 0, 0)
        sizer_2.Add(sizer_5, 0, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnPlot(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        event.Skip()

    def OnClose(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        self.Close()
        event.Skip()

    def OnPathSelection(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        dlg = wx.DirDialog (None, "Choose input directory", "", wx.DD_DEFAULT_STYLE | wx.DD_DIR_MUST_EXIST)
        if dlg.ShowModal() == wx.ID_CANCEL:
            return
        path = dlg.GetPath()
        self.configData.SetPath(path)
        self.configData.Save()
        self.LoadWolkDirTree()
        event.Skip()

    def LoadWolkDirTree(self):
        path = self.configData.GetPath();
        self.txtPath.AppendText(path)
        if (path == ''):
            return
        wolkDirr =  WalkDirectory()
        wolkDirr.wolkDirAppenTree(self.treeDir, path)


    def GridDataInfo(self):
        self.gridDataInfo.InsertRows(1)
        self.gridDataInfo.InsertCols(1)
        self.gridDataInfo.SetColSize(0, 400)
        self.gridDataInfo.SetRowLabelValue(0, 'Size (mm) - X,Y,Z')

    def GridDataInfoUpdate(self, size = (0,0,0), fLength = 0, layersN = 0, printtime = 0):
        strCell = "X:%.2f" % size[0] + " Y:%.2f" % size[1] + " Z:%.2f" % size[2]
        self.gridDataInfo.SetCellValue(0,0, strCell)

    def onTreeChange(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        item =  event.GetItem()
        itemData = self.treeDir.GetItemData(item)
        if (itemData == None):
            return
        filename, file_extension = os.path.splitext(itemData)
        file_extension = file_extension.upper()
        if (file_extension == '.STL'):
            self.windowStlRender.renderthis(itemData)
            size = self.windowStlRender.getObjectSize()
            self.GridDataInfoUpdate(size)
        event.Skip()

    def onTreeChanging(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        event.Skip()

# end of class _3DWarehouseFrame

class MyWhereHouseApp(wx.App):
    def OnInit(self):
        self.frame3DWarehouse = _3DWarehouseFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame3DWarehouse)
        self.frame3DWarehouse.Show()
        return True

# end of class MyWhereHouseApp

if __name__ == "__main__":
    WhereHouseApp = MyWhereHouseApp(0)
    WhereHouseApp.MainLoop()
