#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Tue May 28 11:33:32 2019
#

import wx
import wx.grid
import os
from WalkDirectory import WalkDirectory
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from VTKPanel import VTKPanel
# end wxGlade


class _3DWarehouseFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: _3DWarehouseFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.MAXIMIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((731, 660))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.windowStlRender = VTKPanel(self.panel_1)
        self.txtPath = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.button_Path_selection = wx.Button(self.panel_1, wx.ID_ANY, "...")
        self.treeDir = wx.TreeCtrl(self.panel_1, wx.ID_ANY)
        self.grid_1 = wx.grid.Grid(self.panel_1, wx.ID_ANY, size=(1, 1))
        self.button_calculate = wx.Button(self.panel_1, wx.ID_ANY, "Calculate")
        self.button_test = wx.Button(self.panel_1, wx.ID_ANY, "TEST")
        self.button_close = wx.Button(self.panel_1, wx.ID_ANY, "Close")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnPathSelection, self.button_Path_selection)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.onTreeChange, self.treeDir)
        self.Bind(wx.EVT_TREE_SEL_CHANGING, self.onTreeChanging, self.treeDir)
        self.Bind(wx.EVT_BUTTON, self.OnPlot, self.button_test)
        self.Bind(wx.EVT_BUTTON, self.OnClose, self.button_close)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: _3DWarehouseFrame.__set_properties
        self.SetTitle("3D Warehouse")
        self.txtPath.SetBackgroundColour(wx.Colour(127, 255, 0))
        self.txtPath.Enable(False)
        self.button_Path_selection.SetMinSize((28, 26))
        self.grid_1.CreateGrid(10, 0)
        self.grid_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: _3DWarehouseFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Directory"), wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.windowStlRender, 2, wx.EXPAND, 0)
        sizer_4.Add(self.txtPath, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 0)
        sizer_6.Add((0, 0), 0, 0, 0)
        sizer_6.Add((0, 0), 0, 0, 0)
        sizer_6.Add(self.button_Path_selection, 0, 0, 0)
        sizer_4.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_4.Add(self.treeDir, 1, wx.ALL | wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 4)
        sizer_2.Add(self.grid_1, 0, wx.ALL | wx.EXPAND, 2)
        sizer_5.Add(self.button_calculate, 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add(self.button_test, 0, 0, 0)
        sizer_5.Add(self.button_close, 0, 0, 0)
        sizer_2.Add(sizer_5, 0, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnPlot(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        self.windowStlRender.renderthis()
        event.Skip()

    def OnClose(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        self.Close()
        event.Skip()

    def OnPathSelection(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        dlg = wx.DirDialog (None, "Choose input directory", "", wx.DD_DEFAULT_STYLE | wx.DD_DIR_MUST_EXIST)
        if dlg.ShowModal() == wx.ID_CANCEL:
            return
        self.txtPath.AppendText(dlg.GetPath())
        wolkDirr =  WalkDirectory()
        wolkDirr.wolkDirAppenTree(self.treeDir, dlg.GetPath())
        event.Skip()

    def onTreeChange(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        print("Event handler 'onTreeChange' not implemented!")
        item =  event.GetItem()
        print(self.treeDir.GetItemText(item))
        event.Skip()
        
    def onTreeChanging(self, event):  # wxGlade: _3DWarehouseFrame.<event_handler>
        print("Event handler 'onTreeChanging' not implemented!")
        event.Skip()
# end of class _3DWarehouseFrame

class MyWhereHouseApp(wx.App):
    def OnInit(self):
        self.frame3DWarehouse = _3DWarehouseFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame3DWarehouse)
        self.frame3DWarehouse.Show()
        return True

# end of class MyWhereHouseApp

if __name__ == "__main__":
    WhereHouseApp = MyWhereHouseApp(0)
    WhereHouseApp.MainLoop()
